#!/bin/bash

source variables.inc



##############################################
# Task 1. Perform a backup/restore migration


#RDS_INSTANCE=
#SQL_INSTANCE=

#DB=AdventureWorks2017

#AWS_BUCKET=
#GCP_BUCKET=

#RDS_USER=
#RDS_PASSWORD=

#SQL_USER=
#SQL_PASSWORD=

#GCE_VM_INSTANCE=


# Create a backup of the AdventureWorks2017 database and store it in the AWS S3 bucket named AWS Bucket Name.








# Move this backup file for AdventureWorks2017 database to the Google Cloud Storage bucket named GCS Bucket Name.







# Import the database to the SQL instance Cloud SQL instance, using the backup file stored in GCS Bucket Name bucket. Name the database as AdventureWorks2017 in Cloud SQL instance.

# Hint: The Microsoft Server SQL Management (SSMS) tool is available in the Google Compute Engine VM instance named GCE VM Instance to access the database.
# 


