#
#

PROJECT_ID=`gcloud config get-value project`

##############################################
# Task 1. Perform a backup/restore migration


RDS_INSTANCE=
SQL_INSTANCE=

DB=AdventureWorks2017

AWS_BUCKET=
GCP_BUCKET=

RDS_USER=
RDS_PASSWORD=

SQL_USER=
SQL_PASSWORD=

GCE_VM_INSTANCE=

##############################################################
# Task 2. Transfer credentials between instances of SQL Server


LOGIN=
PASS=


#####################################################
# Task 3. Install the SQL Server Maintenance Solution

NEW_DB=dbtools



##########################################
# Task 4. Review and configure the backups
