#
#

REGION=

# Task 1. Load data into BigQuery using BigQuery Data Transfer Service
# file table1.json
GCS=
table1=
dataset=

# Task 2. Build and run a streaming (unbound) Dataflow pipeline

topic1=
table2=

# Task 3. Load data from Cloud SQL to BigQuery using Datastream
instance=
topic2=
sub2=

sourcecp=
instance=
username=
password=
ip=
destinationcp=

stream=


PROJECT_ID=`gcloud config get-value project`